"""Recreate migrations

Revision ID: 54dae7a5e89f
Revises: 
Create Date: 2024-08-11 11:40:28.054539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54dae7a5e89f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('before', 'ongoing', 'completed', name='status_enum'), nullable=False))
        batch_op.drop_index('event_id')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.create_index('event_id', ['event_id'], unique=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
