"""added authorization

Revision ID: 738f1d588082
Revises: ccaad539bae6
Create Date: 2024-08-20 23:00:33.331418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738f1d588082'
down_revision = 'ccaad539bae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
