"""added overlap attribute

Revision ID: ccaad539bae6
Revises: cd6453be4b2d
Create Date: 2024-08-17 01:45:21.644625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccaad539bae6'
down_revision = 'cd6453be4b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
